exclude_patterns:
  - "**/node_modules/"
  - "node_modules/"
  - "script/"
  - "**/*.d.ts"
  - "**/testing/"
  - "**/*.spec.js"
  - "database/"
  - "**/migrations/"
  - "**/seeds/"
  - "*.md"
  - "*.json"
  - "migration-files-backup.js"
