version: "3.7"
services:
    
    node:
        build:
            context: . 
            dockerfile: Dockerfile
        depends_on: 
            - postgres
        ports:
            - "4000:4000"
        networks:
            - nodeapp-network
    
    postgres:
        image: postgres
        environment: 
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        ports:
            - "5432:5432"
        networks:
            - nodeapp-network
    
networks: 
    nodeapp-network:
        driver: bridge
            